Validations and model specs
Loltolo-Lesapiti/blog_app pull request #3
Opened 2022-12-14 21:41 UTC by Loltolo-Lesapiti

This project creates a blog-app website.A fully functional website that will show the list of post and users can interact by adding comments and liking posts. This milestone implements modal validation and testing.

2022-12-14 21:46 UTC, prolajumokeoni reviewed
Hi @Loltolo-Lesapiti 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that does not follow proper Gitflow, and a professional readme
Kindly make sure that all headers of the microverse [readme](https://github.com/microverseinc/readme-template) template is present in your readme,
Please personalize the the content of the sections

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-14 22:39 UTC, mirouhml commented
Hi @Loltolo-Lesapiti, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

As the previous reviewer mentioned, you have submitted a project, that doesn't follow proper Gitflow, you need to have a main and a dev (development) branch and then the features branches should all be merged to the dev branch and not the main branch, in your case you opened a PR to the main branch and from what I see you don't have a dev branch, kindly fix this.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-16 06:02 UTC, peterrobert commented on spec/models/comment_spec.rb
>  RSpec.describe Comment, type: :model do
This change has not yet been done

2022-12-16 06:06 UTC, peterrobert commented on spec/models/post_spec.rb
> -
This change has been done well

2022-12-16 06:08 UTC, peterrobert commented on spec/models/user_spec.rb
>    subject(:user) { User.create(name: 'Loltolo', photo: 'https://avatars.githubusercontent.com/u/25284722?s=40&v=4', bio: 'Full stack developer', post_counter: 1) }
some of the changes has been done well

2022-12-16 06:19 UTC, peterrobert requested changes
Hi @Loltolo-Lesapiti, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] It will be great to fix the failing tests. Just like mentioned by the previous reviewer, some of your tests are failing. Kindly fix all the failing tests. Kindly see the screenshot below ⬇️ 

![testfailing](https://user-images.githubusercontent.com/32361963/208034047-77addeab-f561-49e6-bedd-5467bc07863f.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 06:19 UTC, peterrobert commented on app/models/post.rb
>      post.increment!(:posts_counter)
- [ ] It will be great to test this method. As required by the previous reviewer, the `update_post_counter` method should also be tested in your spec files. Kindly add tests for this method

2022-12-16 06:19 UTC, peterrobert commented on app/models/user.rb
>      posts.order(created_at: :desc).limit(3)
- [ ] It will be great to add tests for this method also. As requested by the previous reviewer, there should be tests for this method in your user spec file. Kindly add tests for this method

2022-12-16 06:19 UTC, peterrobert commented on spec/models/like_spec.rb
>      expect(like).to_not be_valid
- [ ] It will be great to add a test for your`update_like_counter` method as requested by the previous reviewer. This will ensure that all the methods in your like model are tested

2022-12-16 06:48 UTC, Loltolo-Lesapiti commented
Hi @peterrobert 
There are no failing tests on my side. 
![image](https://user-images.githubusercontent.com/25284722/208039228-4ee2c34b-e04a-49ac-90fa-b98e264ef49e.png)

2022-12-16 06:56 UTC, peterrobert commented
hey, @Loltolo-Lesapiti kindly just to be sure, clone the project again from your GitHub then install the project again and try to run the tests. Let me know if the tests pass

2022-12-16 10:21 UTC, Nemwel-Boniface approved these changes
## Hello @Loltolo-Lesapiti               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 16:25 UTC, merged